enum ActionsTypes {
  PRODUCT_PAGE_DATA = "PRODUCT_PAGE_DATA",
  PRODUCTS_PAGINATION = "PRODUCTS_PAGINATION",
  UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST",
  UPDATE_FILTER_ON_LOAD = "UPDATE_FILTER_ON_LOAD",

  // cart
  ADD_TO_CART = "ADD_TO_CART",
  COUNT_CART_TOTALS = "COUNT_CART_TOTALS",
  REMOVE_CART_ITEM = "REMOVE_CART_ITEM",
  TOGGLE_ITEM_AMOUNT = "TOGGLE_ITEM_AMOUNT",
  ORDER_COMPLETED = "ORDER_COMPLETED",
  TOGGLE_CHECKOUT_BUTTON = "TOGGLE_CHECKOUT_BUTTON",
  TOGGLE_CART_LOADING = "TOGGLE_CART_LOADING",

  // AUTH USer
  SET_USER = "SET_USER",
  USER_LOGGED_OUT = "USER_LOGGED_OUT",
  TOGGLE_AUTH_FORM = "TOGGLE_AUTH_FORM",
  TOGGLE_IS_LOADING = "TOGGLE_IS_LOADING",
  AUTH_ERROR_MESSAGE = "AUTH_ERROR_MESSAGE",
  TOGGLE_SHOW_FORGOT_PASSWORD_FORM = "TOGGLE_SHOW_FORGOT_PASSWORD_FORM",
  SHOW_REGISTRATION_FORM = "SHOW_REGISTRATION_FORM",
  SENT_PASSWORD_EMAIL = "SENT_PASSWORD_EMAIL",
  DELETE_PRODUCT_START = "DELETE_PRODUCT_START",
  DELETE_PRODUCT_END = "DELETE_PRODUCT_END",
  DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR",

  // Admin USer
  UPDATE_PRODUCT_DETAILS = "UPDATE_PRODUCT_DETAILS",
  SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT",
  UPDATE_PRODUCT_IMAGE = "UPDATE_PRODUCT_IMAGE",
  UPDATE_PRODUCT_IMAGE_STARTED = "UPDATE_PRODUCT_IMAGE_STARTED",

  REGISTRATION_SUCCESSES = "REGISTRATION_SUCCESSES",

  UPDATING_PRODUCT_END = "UPDATING_PRODUCT_END",
  UPDATING_PRODUCT_STARTED = "UPDATING_PRODUCT_STARTED",

  // Global
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  TOGGLE_MOBILE_NAV = "TOGGLE_MOBILE_NAV",
  HIDE_TOP_MESSAGE = "HIDE_TOP_MESSAGE",
}

export default ActionsTypes;
